create table public.formatos (
  codigo text primary key,
  nombre text not null,
  medicamentos text not null,
  sala text not null
);

alter table public.formatos enable row level security;

create policy "formatos_select_anon" on public.formatos
  for select to anon, authenticated using (true);

insert into public.formatos (codigo, nombre, medicamentos, sala) values
  ('ASS RSA FM004', 'FORMULARIO UNICO DE MEDICAMENTOS', 'TODOS', 'SEM/SEMNNIMB'),
  ('ASS RSA FM062', 'FORMATO PARA PRESENTACIÓN Y EVALUACIÓN DE MODIFICACIONES AL REGISTRO SANITARIO PARA LA DIRECCIÓN DE MEDICAMENTOS Y PRODUCTOS BIOLOGICOS', 'BIOLOGICOS Y BIOTECNOLOGICOS', 'SEMNNIMB'),
  ('ASS RSA FM076', 'FORMATO DE SOLICITUD DE REGISTRO O RENOVACION DE VACUNAS', 'BIOLOGICOS Y BIOTECNOLOGICOS', 'SEMNNIMB'),
  ('ASS RSA FM080', 'FORMATO DE EVALUACION Y PRESENTACION DE LA EVALUACIÓN FARMACOLÓGICA PARA NUEVA ASOCIACION, NUEVA FORMA FARMACEUTICA Y NUEVA CONCENTRACION PARA MEDICAMENTOS DE SÍNTESIS -SEM', 'SINTESIS QUIMICA', 'SEM'),
  ('ASS RSA FM081', 'FORMATO DE PRESENTACION DE LA EVALUACIÓN FARMACOLÓGICA DE MOLÉCULA NUEVA PARA MEDICAMENTOS DE SÍNTESIS - SEMNNIMB', 'SINTESIS QUIMICA', 'SEMNNIMB'),
  ('ASS RSA FM110', 'FORMATO DE PRESENTACION DE SOLICITUD UNIFICADA DE EVALUACIÓN FARMACOLÓGICA Y REGISTRO SANITARIO O RENOVACIÓN PARA MEDICAMENTOS BIOLÓGICOS', 'BIOLOGICOS Y BIOTECNOLOGICOS', 'SEMNNIMB'),
  ('ASS RSA FM113', 'FORMATO GENERAL PARA SOLICITUDES DE PRODUCTOS BIOLÓGICOS', 'BIOLOGICOS Y BIOTECNOLOGICOS', 'SEMNNIMB');

alter table public.expedientes
  add column formato_codigo text references public.formatos(codigo);

alter table public.expedientes drop column ruta_evaluacion;
